-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%'
ORDER BY WAREHOUSE_ID ASC;

-- 
-- COALESCE 함수는 SQL에서 사용되는 함수로, 인수로 주어진 값들 중 첫 번째로 NULL이 아닌 값을 반환합